syntax = "proto3";

package digital_music_stand.band;
option go_package = "github.com/ziomciopoziomcio/digital-music-stand/contracts/gen/bandpb";

service BandService {
  rpc CreateBand(CreateBandRequest) returns (CreateBandResponse);
  rpc InviteMember(InviteMemberRequest) returns (InviteMemberResponse);
  rpc ListMyInvitations(ListMyInvitationsRequest) returns (ListMyInvitationsResponse);
  rpc RespondToInvitation(RespondToInvitationRequest) returns (RespondToInvitationResponse);
  rpc ListMyBands(ListMyBandsRequest) returns (ListMyBandsResponse);
}

message CreateBandRequest {
  string name = 1;
}

message CreateBandResponse {
  uint32 id = 1;
  string message = 2;
}

message InviteMemberRequest {
  uint32 band_id = 1;
  string invitee_email = 2;
}

message InviteMemberResponse {
  string message = 1;
}

message ListMyInvitationsRequest {}

message Invitation {
  uint32 id = 1;
  string band_name = 2;
  string status = 3;
}

message ListMyInvitationsResponse {
  repeated Invitation invitations = 1;
}

message RespondToInvitationRequest {
  uint32 invitation_id = 1;
  bool accept = 2;
}

message RespondToInvitationResponse {
  string message = 1;
}

message ListMyBandsRequest {}

message Band {
  uint32 id = 1;
  string name = 2;
  bool is_manager = 3;
}

message ListMyBandsResponse {
  repeated Band bands = 1;
}