syntax = "proto3";

package digital_music_stand.score;
option go_package = "github.com/ziomciopoziomcio/digital-music-stand/contracts/gen/scorepb";

service ScoreService {
  rpc CreateScore(CreateScoreRequest) returns (CreateScoreResponse);
  rpc ListMyScores(ListMyScoresRequest) returns (ListMyScoresResponse);
  rpc ShareScore(ShareScoreRequest) returns (ShareScoreResponse);
}

message CreateScoreRequest {
  string name = 1;
  string composer = 2;
  string file_path = 3;
  uint32 owner_id = 4;
}

message CreateScoreResponse {
  uint32 id = 1;
  string message = 2;
}

message ListMyScoresRequest {
  uint32 user_id = 1;
}

message ListMyScoresResponse {
  repeated Score scores = 1;
}

message Score {
  uint32 id = 1;
  string name = 2;
  string composer = 3;
  string file_path = 4;
}

message ShareScoreRequest {
  uint32 score_id = 1;

  optional uint32 user_id = 2;
  optional uint32 band_id = 3;
}

message ShareScoreResponse {
  string message = 1;
}
