syntax = "proto3";

package digital_music_stand.score;
option go_package = "github.com/ziomciopoziomcio/digital-music-stand/contracts/gen/scorepb";

service ScoreService {
  rpc CreateScore(CreateScoreRequest) returns (CreateScoreResponse);
  rpc UpdateScore(UpdateScoreRequest) returns (UpdateScoreResponse);
  rpc DeleteScore(DeleteScoreRequest) returns (DeleteScoreResponse);
  rpc ListMyScores(ListMyScoresRequest) returns (ListMyScoresResponse);
  rpc DownloadScore(DownloadScoreRequest) returns (stream DownloadScoreResponse);

  rpc ShareScore(ShareScoreRequest) returns (ShareScoreResponse);
  rpc RevokeScoreAccess(RevokeScoreAccessRequest) returns (RevokeScoreAccessResponse);

  rpc ListScoreInvitations(ListScoreInvitationsRequest) returns (ListScoreInvitationsResponse);
  rpc RespondToScoreInvitation(RespondToScoreInvitationRequest) returns (RespondToScoreInvitationResponse);
}

message CreateScoreRequest {
  optional string id = 7;
  string name = 1;
  string composer = 2;
  bytes file_data = 5;
  string file_extension = 6;
}

message CreateScoreResponse {
  string id = 1;
  string message = 2;
  string checksum = 3;
}

message UpdateScoreRequest {
  string id = 1;
  string name = 2;
  optional string composer = 3;
}

message UpdateScoreResponse {
  string message = 1;
  string checksum = 2;
}

message DeleteScoreRequest {
  string id = 1;
}

message DeleteScoreResponse {
  string message = 1;
}

message ListMyScoresRequest {}

message Score {
  string id = 1;
  string name = 2;
  string composer = 3;
  string file_path = 4;
  string checksum = 5;
  string file_extension = 6;
  bool is_owner = 7;
}

message ListMyScoresResponse {
  repeated Score scores = 1;
}

message DownloadScoreRequest {
  string score_id = 1;
}

message DownloadScoreResponse {
  bytes chunk_data = 1;
}

message ShareScoreRequest {
  string score_id = 1;
  optional string target_email = 2;
  optional uint32 target_band_id = 3;
}

message ShareScoreResponse {
  string message = 1;
}

message RevokeScoreAccessRequest {
  string score_id = 1;
  optional string target_email = 2;
  optional uint32 target_band_id = 3;
}

message RevokeScoreAccessResponse {
  string message = 1;
}

message ListScoreInvitationsRequest {}

message ScoreInvitation {
  uint32 id = 1;
  string score_id = 2;
  string score_name = 3;
  string owner_email = 4;
}

message ListScoreInvitationsResponse {
  repeated ScoreInvitation invitations = 1;
}

message RespondToScoreInvitationRequest {
  uint32 invitation_id = 1;
  bool accept = 2;
}

message RespondToScoreInvitationResponse {
  string message = 1;
}