syntax = "proto3";

package digital_music_stand.sync;

option go_package = "github.com/ziomciopoziomcio/digital-music-stand/contracts/gen/syncpb";

service LiveSyncService {
  rpc SyncConcertStream (stream SyncRequest) returns (stream SyncResponse);
}

enum ActionType {
  UNKNOWN_ACTION = 0;
  STATE_UPDATE = 1;
  METRONOME_TICK = 2;
  STOP_LEADING = 3;
}

message SyncRequest {
  string concert_id = 1;
  ActionType action = 2;
  uint32 page_number = 3;
  uint32 item_index = 4;
  uint32 timer_seconds = 5;
  bool is_accent = 6;
  bool is_leader = 7;
}

message SyncResponse {
  string concert_id = 1;
  uint32 sender_id = 2;
  ActionType action = 3;
  uint32 page_number = 4;
  uint32 item_index = 5;
  uint32 timer_seconds = 6;
  bool is_accent = 7;
  bool is_leader = 8;
  int64 timestamp_ms = 9;
}