syntax = "proto3";

package digital_music_stand.sync;
option go_package = "github.com/ziomciopoziomcio/digital-music-stand/contracts/gen/syncpb";


service LiveSyncService {
  rpc SyncConcertStream (stream SyncRequest) returns (stream SyncResponse);
}


enum ActionType {
  UNKNOWN_ACTION = 0;
  TURN_PAGE = 1;
  JUMP_TO_MEASURE = 2;
  METRONOME_TICK = 3;
  START_CONCERT = 4;
  STOP_CONCERT = 5;
}

message SyncRequest {
  uint32 concert_id = 1;
  uint32 user_id = 2;
  ActionType action = 3;

  optional uint32 page_number = 4;
  optional uint32 measure_number = 5;
}

message SyncResponse {
  uint32 concert_id = 1;
  uint32 sender_id = 2;
  ActionType action = 3;

  optional uint32 page_number = 4;
  optional uint32 measure_number = 5;

  int64 timestamp_ms = 6;
}