syntax = "proto3";

package digital_music_stand.user;
option go_package = "github.com/ziomciopoziomcio/digital-music-stand/contracts/gen/userpb";

service UserService {
  rpc RegisterUser(RegisterUserRequest) returns (RegisterUserResponse);
  rpc LoginUser(LoginUserRequest) returns (LoginUserResponse);
  rpc GetProfile(GetProfileRequest) returns (GetProfileResponse);
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse);
  rpc ApproveUser(ApproveUserRequest) returns (ApproveUserResponse);
  rpc RejectUser(RejectUserRequest) returns (RejectUserResponse);
  rpc ChangePassword(ChangePasswordRequest) returns (ChangePasswordResponse);
  rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse);
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse);
}

message RegisterUserRequest {
  string email = 1;
  string password = 2;
  string name = 3;
  string surname = 4;
}

message RegisterUserResponse {
  uint32 id = 1;
  string message = 2;
}

message LoginUserRequest {
  string email = 1;
  string password = 2;
}

message LoginUserResponse {
  string token = 1;
  string refresh_token = 2;
}

message GetProfileRequest {
  reserved 1;
  reserved "id";
}

message GetProfileResponse {
  uint32 id = 1;
  string email = 2;
  string name = 3;
  string surname = 4;
  string status = 5;
  string role = 6;
}

message UserInfo {
  uint32 id = 1;
  string email = 2;
  string name = 3;
  string surname = 4;
  string status = 5;
  string role = 6;
}

message ListUsersRequest {
  string status_filter = 1;
}

message ListUsersResponse {
  repeated UserInfo users = 1;
}

message ApproveUserRequest {
  uint32 user_id = 1;
}

message ApproveUserResponse {
  string message = 1;
}

message RejectUserRequest {
  uint32 user_id = 1;
}

message RejectUserResponse {
  string message = 1;
}

message ChangePasswordRequest {
  string old_password = 1;
  string new_password = 2;
}

message ChangePasswordResponse {
  string message = 1;
}

message ResetPasswordRequest {
  string email = 1;
}

message ResetPasswordResponse {
  string message = 1;
}

message RefreshTokenRequest {
  string refresh_token = 1;
}

message RefreshTokenResponse {
  string token = 1;
  string refresh_token = 2;
}
