name: Backend CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-check:
    name: Build & Format check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
          cache-dependency-path: server/go.sum

      - name: Verify dependencies
        run: go mod verify

      - name: Check code formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Code is not formatted. Please run 'go fmt' to format the code."
            go fmt -d .
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Build the server
        run: go build -v ./cmd/api
